@startuml "Sistema de Gerenciamento do Plano de Atividade Docente"
    title "<b>Sistema de Gerenciamento do Plano de Atividade Docente</b>"
    
    left to right direction

    'PAD
    (Manter PAD) as mPad
    (Incluir PAD) as iPad
    (Alterar PAD) as aPad
    (Excluir PAD) as ePad
    (Listar PAD) as lPad
    (Pesquisar PAD) as pPad

    (Corrigir PAD) as corrigePad

    (Submeter PAD) as envPad
    (Monitorar Revisões PADs) as revPad
    (Validar PAD) as valiPad
    (Monitorar Submissões de PADs) as moniPad
    (Monitorar Correções de PADs) as moniCorrPad

    (Homologar PAD) as homoPad
    (Monitorar Homologacao de PADs) as moniHomPad
    (Gerar Relatorio PADs) as gerarRelatorioPad
    (Consultar PADs) as consultarPad

    'Cronograma
    (Manter Cronograma) as mantCron
    (Incluir Cronograma) as iCron
    (Alterar Cronograma) as aCron
    (Excluir Cronograma) as eCron
    (Listar Cronograma) as lCron

    'Dados abertos
    (Consultar Informações) as consultInfo

    'Administração
    (Autenticar) as autent
    (Auto Registrar) as registrar
    (Manter Usuario) as mantUsuario
    (Incluir Usuário) as iUsuario
    (Alterar Usuário) as aUsuario
    (Excluir Usuário) as eUsuario
    (Listar Usuário) as lUsuario
    (Pesquisar Usuário) as pUsuario
    (Bloquear Usuário) as bloqUsuario
    (Desbloquear Usuário) as desbloqUsuario

    (Manter Gestores) as mantGestores
    (Manter Coordenadores) as mantCoordenadores
    (Manter Dados Cadastrais) as mantCadastro
    (Alternar Perfil) as alternarPerfil
    (Manter Configuracaoes) as manterConfiguracoes

    'Sistema
    (Importar Usuarios) as (importUsuarios) <<Batch>>
    (Importar Cursos) as (importCursos) <<Batch>>
    (Importar Componentes Curriculares) as (importCompCurr) <<Batch>>
    
    'Atores
    actor Professor as prof
    actor "Coordenador Curso" as cc
    actor "Coordenador Setorial" as cs
    actor "Comunidade Academica" as ca
    actor "Gestor" as gest
    actor "Administrador" as adm
    actor "Sistema" as sistema

    'atores
    prof <|-right- cc
    cc <|-right- cs
    prof -left-|> ca
    gest -left-|> cs
    adm --|> gest

    'professor
    prof --> mPad
    prof --> corrigePad    

    prof --> envPad
    prof --> moniCorrPad
    prof -up-> autent
    autent .left.> registrar : <<extend>>
    prof --> mantCadastro

    mPad <.. iPad : <<extend>>
    mPad <.. aPad : <<extend>>
    mPad <.. ePad : <<extend>>
    mPad ..> lPad : <<include>>
    mPad <.. pPad : <<extend>>

    'comunidade academica
    ca --> consultInfo

    'coordenador de curso
    cc -up-> moniPad
    cc -up-> consultarPad
    cc -up-> alternarPerfil

    'coordenador setorial
    cs --> revPad
    cs --> valiPad

    'gestor
    gest --> homoPad
    gest --> mantCron
    gest --> gerarRelatorioPad
    gest --> moniHomPad
    gest --> mantCoordenadores

    mantCron <.. iCron : <<extend>>
    mantCron <.. aCron : <<extend>>
    mantCron <.. eCron : <<extend>>
    mantCron ..> lCron : <<include>>

    'administrador
    adm --> mantUsuario
    adm --> bloqUsuario
    adm --> desbloqUsuario
    adm --> mantGestores
    
    mantUsuario <.. iUsuario : <<extend>>
    mantUsuario <.. aUsuario : <<extend>>
    mantUsuario <.. eUsuario : <<extend>>
    mantUsuario ..> lUsuario : <<include>>
    mantUsuario <.. pUsuario : <<extend>>

    'sistema
    sistema --> importUsuarios
    sistema --> importCursos
    sistema --> importCompCurr
    sistema --> manterConfiguracoes

@enduml
